trigger:
  batch: true
  branches:
    include:
    - main
    - develop
    - release/*
  paths:
    exclude:
    - README.md

pool:
  name: Default
  demands:
  - cmake

variables:
  buildPlatform: 'x64'
  
steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 6.0.0'
  inputs:
    versionSpec: '6.0.0'
    checkLatest: true

- task: GitVersion@5
  inputs:
    runtime: 'full'
    configFilePath: 'GitVersion.yml'

- script: echo %Action%%BuildVersion%
  displayName: 'Set build version'
  env:
    Action: '##vso[build.updatebuildnumber]'
    BuildVersion: $(GitVersion.NugetVersionV2)

- task: run-cmake@0
  inputs:
    cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
    cmakeBuildType: 'Release'
    cmakeGenerator: 'Ninja'
