trigger:
  batch: true
  branches:
    include:
    - main
    - develop
    - release/*
  paths:
    exclude:
    - README.md

pool:
  name: Default
  demands:
  - cmake

variables:
  buildPlatform: 'x64'
  
steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.10.0'
  inputs:
    versionSpec: '5.10.0'
    checkLatest: true

- task: GitVersion@5
  inputs:
    runtime: 'core'
    configFilePath: 'GitVersion.yml'

- script: echo %Action%%BuildVersion%
  displayName: 'Set build version'
  env:
    Action: '##vso[build.updatebuildnumber]'
    BuildVersion: $(GitVersion.NugetVersionV2)

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'ec2759e0-0587-4306-8a8d-8695f15e2336'
  continueOnError: true

- task: run-cmake@0
  inputs:
    cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
    cmakeBuildType: 'Release'
    cmakeGenerator: 'Ninja'
